CREATE DATABASE IF NOT EXISTS hos
  DEFAULT CHARACTER SET UTF8
  COLLATE UTF8_GENERAL_CI;

USE hos;

--
-- Table structure for table `USER_INFO`
--
DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE USER_INFO
(
  UserId  VARCHAR(32) NOT NULL,
  UserName  VARCHAR(32) NOT NULL,
  Password    VARCHAR(64) NOT NULL
  COMMENT 'PASSWORD md5',
  SystemRole VARCHAR(32) NOT NULL
  COMMENT 'ADMIN OR USER',
  CreateTime TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DETAIL      VARCHAR(256),
  PRIMARY KEY (UserId),
  UNIQUE KEY AK_UQ_USER_NAME (UserName)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COMMENT = '用户信息';

--
-- Table structure for table `TOKEN_INFO`
--

DROP TABLE IF EXISTS TOKEN_INFO;

CREATE TABLE TOKEN_INFO
(
  Token        VARCHAR(32) NOT NULL,
  ExpireTime  INT(11)     NOT NULL,
  CreateTime  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RefreshTime TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Active       TINYINT     NOT NULL,
  Creator      VARCHAR(32) NOT NULL,
  PRIMARY KEY (Token)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COMMENT = 'token 信息表';

--
-- Table structure for table `HOS_BUCKET`
--

DROP TABLE IF EXISTS HOS_BUCKET;

CREATE TABLE HOS_BUCKET (
  BucketId   VARCHAR(32),
  BucketName VARCHAR(32),
  CreateTime TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Detail      VARCHAR(256),
  Creator     VARCHAR(32) NOT NULL,
  UNIQUE KEY AK_KEY_BUCKET_NAME(BucketName),
  PRIMARY KEY (BucketId)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COMMENT = 'HOS BUCKET';

--
-- Table structure for table SERVICE_AUTH
--

DROP TABLE IF EXISTS SERVICE_AUTH;

CREATE TABLE SERVICE_AUTH
(
  BucketName  VARCHAR(32) NOT NULL,
  TargetToken VARCHAR(32) NOT NULL COMMENT '被授权对象token',
  AuthTime    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (BucketName, TargetToken)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COMMENT = '对象存储服务授权表';

